Revert migration of cssnano v4.1.11 to v6.0.1
* Arrow functions (and possibly other ES6 features) are not being converted to ES5.
* This causes error 'Fatal error: plugin is not a function' when using v6.0.1